pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base = main
      - "#approved-reviews-by >= 1"
      - check-success = Max TF pre-commit
      - check-success = Validate PR title
      - draft == false
      - label != do-not-merge
    actions:
      merge:
        method: squash

  - name: Automatically approve minor/patch Renovate PRs
    conditions:
      - base = main
      - author = renovate[bot]
      - draft == false
      - label != do-not-merge
      - or:
          - label = update-minor
          - label = update-patch
          - label = update-digest
    actions:
      review:
        type: APPROVE
        message: Automatically approved (non-major Renovate update)

  - name: Automatic merge Renovate PRs (non-major)
    conditions:
      - base = main
      - author = renovate[bot]
      - check-success = Max TF pre-commit
      - check-success = Validate PR title
      - draft == false
      - label != do-not-merge
      - or:
          - label = update-minor
          - label = update-patch
          - label = update-digest
    actions:
      merge:
        method: squash

  - name: Automatic merge on approval release
    conditions:
      - base = release
      - "#approved-reviews-by >= 1"
      - draft == false
    actions:
      merge:
        method: merge
